/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin-login'
import { Route as ResidentAccessRouteImport } from './routes/resident-access'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ManagerAuthRouteImport } from './routes/manager-auth'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CommunityVoiceRouteImport } from './routes/community-voice'
import { Route as CommunityStandardsRouteImport } from './routes/community-standards'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PulseBuildingIdRouteImport } from './routes/pulse.$buildingId'
import { Route as OnboardingBuildingIdRouteImport } from './routes/onboarding.$buildingId'
import { Route as MessagesConnectionIdRouteImport } from './routes/messages.$connectionId'
import { Route as ManagerBuildingIdRouteImport } from './routes/manager.$buildingId'
import { Route as ForumThreadIdRouteImport } from './routes/forum.$threadId'
import { Route as BuildingBuildingIdRouteImport } from './routes/building.$buildingId'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as ManagerBuildingIdIndexRouteImport } from './routes/manager.$buildingId.index'
import { Route as ManagerBuildingIdRecognitionRouteImport } from './routes/manager.$buildingId.recognition'
import { Route as ManagerBuildingIdCommunityVoiceRouteImport } from './routes/manager.$buildingId.community-voice'
import { Route as ManagerBuildingIdCommunityIntelligenceRouteImport } from './routes/manager.$buildingId.community-intelligence'
import { Route as ManagerBuildingIdBrandingRouteImport } from './routes/manager.$buildingId.branding'
import { Route as AdminBuildingsBuildingIdRouteImport } from './routes/admin.buildings.$buildingId'
import { Route as AdminBuildingsBuildingIdIndexRouteImport } from './routes/admin.buildings.$buildingId.index'
import { Route as ApiPublicManifestBuildingIdRouteImport } from './routes/api/public/manifest.$buildingId'
import { Route as AdminBuildingsBuildingIdSettingsRouteImport } from './routes/admin.buildings.$buildingId.settings'
import { Route as AdminBuildingsBuildingIdResidentsRouteImport } from './routes/admin.buildings.$buildingId.residents'
import { Route as AdminBuildingsBuildingIdPulseRouteImport } from './routes/admin.buildings.$buildingId.pulse'
import { Route as AdminBuildingsBuildingIdPlaybookRouteImport } from './routes/admin.buildings.$buildingId.playbook'
import { Route as AdminBuildingsBuildingIdNeighborhoodRouteImport } from './routes/admin.buildings.$buildingId.neighborhood'
import { Route as AdminBuildingsBuildingIdManagersRouteImport } from './routes/admin.buildings.$buildingId.managers'
import { Route as AdminBuildingsBuildingIdLegalRouteImport } from './routes/admin.buildings.$buildingId.legal'
import { Route as AdminBuildingsBuildingIdEventsRouteImport } from './routes/admin.buildings.$buildingId.events'
import { Route as AdminBuildingsBuildingIdDangerRouteImport } from './routes/admin.buildings.$buildingId.danger'
import { Route as AdminBuildingsBuildingIdBrandingRouteImport } from './routes/admin.buildings.$buildingId.branding'
import { Route as AdminBuildingsBuildingIdAnalyticsRouteImport } from './routes/admin.buildings.$buildingId.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin-login',
  path: '/super-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentAccessRoute = ResidentAccessRouteImport.update({
  id: '/resident-access',
  path: '/resident-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAuthRoute = ManagerAuthRouteImport.update({
  id: '/manager-auth',
  path: '/manager-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityVoiceRoute = CommunityVoiceRouteImport.update({
  id: '/community-voice',
  path: '/community-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStandardsRoute = CommunityStandardsRouteImport.update({
  id: '/community-standards',
  path: '/community-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PulseBuildingIdRoute = PulseBuildingIdRouteImport.update({
  id: '/pulse/$buildingId',
  path: '/pulse/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuildingIdRoute = OnboardingBuildingIdRouteImport.update({
  id: '/onboarding/$buildingId',
  path: '/onboarding/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConnectionIdRoute = MessagesConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => MessagesRoute,
} as any)
const ManagerBuildingIdRoute = ManagerBuildingIdRouteImport.update({
  id: '/$buildingId',
  path: '/$buildingId',
  getParentRoute: () => ManagerRoute,
} as any)
const ForumThreadIdRoute = ForumThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ForumRoute,
} as any)
const BuildingBuildingIdRoute = BuildingBuildingIdRouteImport.update({
  id: '/building/$buildingId',
  path: '/building/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerBuildingIdIndexRoute = ManagerBuildingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerBuildingIdRoute,
} as any)
const ManagerBuildingIdRecognitionRoute =
  ManagerBuildingIdRecognitionRouteImport.update({
    id: '/recognition',
    path: '/recognition',
    getParentRoute: () => ManagerBuildingIdRoute,
  } as any)
const ManagerBuildingIdCommunityVoiceRoute =
  ManagerBuildingIdCommunityVoiceRouteImport.update({
    id: '/community-voice',
    path: '/community-voice',
    getParentRoute: () => ManagerBuildingIdRoute,
  } as any)
const ManagerBuildingIdCommunityIntelligenceRoute =
  ManagerBuildingIdCommunityIntelligenceRouteImport.update({
    id: '/community-intelligence',
    path: '/community-intelligence',
    getParentRoute: () => ManagerBuildingIdRoute,
  } as any)
const ManagerBuildingIdBrandingRoute =
  ManagerBuildingIdBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => ManagerBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdRoute =
  AdminBuildingsBuildingIdRouteImport.update({
    id: '/buildings/$buildingId',
    path: '/buildings/$buildingId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBuildingsBuildingIdIndexRoute =
  AdminBuildingsBuildingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const ApiPublicManifestBuildingIdRoute =
  ApiPublicManifestBuildingIdRouteImport.update({
    id: '/api/public/manifest/$buildingId',
    path: '/api/public/manifest/$buildingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBuildingsBuildingIdSettingsRoute =
  AdminBuildingsBuildingIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdResidentsRoute =
  AdminBuildingsBuildingIdResidentsRouteImport.update({
    id: '/residents',
    path: '/residents',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdPulseRoute =
  AdminBuildingsBuildingIdPulseRouteImport.update({
    id: '/pulse',
    path: '/pulse',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdPlaybookRoute =
  AdminBuildingsBuildingIdPlaybookRouteImport.update({
    id: '/playbook',
    path: '/playbook',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdNeighborhoodRoute =
  AdminBuildingsBuildingIdNeighborhoodRouteImport.update({
    id: '/neighborhood',
    path: '/neighborhood',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdManagersRoute =
  AdminBuildingsBuildingIdManagersRouteImport.update({
    id: '/managers',
    path: '/managers',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdLegalRoute =
  AdminBuildingsBuildingIdLegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdEventsRoute =
  AdminBuildingsBuildingIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdDangerRoute =
  AdminBuildingsBuildingIdDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdBrandingRoute =
  AdminBuildingsBuildingIdBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdAnalyticsRoute =
  AdminBuildingsBuildingIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminBuildingsBuildingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/community-voice': typeof CommunityVoiceRoute
  '/connections': typeof ConnectionsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRouteWithChildren
  '/messages/$connectionId': typeof MessagesConnectionIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
  '/pulse/$buildingId': typeof PulseBuildingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/buildings/$buildingId': typeof AdminBuildingsBuildingIdRouteWithChildren
  '/manager/$buildingId/branding': typeof ManagerBuildingIdBrandingRoute
  '/manager/$buildingId/community-intelligence': typeof ManagerBuildingIdCommunityIntelligenceRoute
  '/manager/$buildingId/community-voice': typeof ManagerBuildingIdCommunityVoiceRoute
  '/manager/$buildingId/recognition': typeof ManagerBuildingIdRecognitionRoute
  '/manager/$buildingId/': typeof ManagerBuildingIdIndexRoute
  '/admin/buildings/$buildingId/analytics': typeof AdminBuildingsBuildingIdAnalyticsRoute
  '/admin/buildings/$buildingId/branding': typeof AdminBuildingsBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/danger': typeof AdminBuildingsBuildingIdDangerRoute
  '/admin/buildings/$buildingId/events': typeof AdminBuildingsBuildingIdEventsRoute
  '/admin/buildings/$buildingId/legal': typeof AdminBuildingsBuildingIdLegalRoute
  '/admin/buildings/$buildingId/managers': typeof AdminBuildingsBuildingIdManagersRoute
  '/admin/buildings/$buildingId/neighborhood': typeof AdminBuildingsBuildingIdNeighborhoodRoute
  '/admin/buildings/$buildingId/playbook': typeof AdminBuildingsBuildingIdPlaybookRoute
  '/admin/buildings/$buildingId/pulse': typeof AdminBuildingsBuildingIdPulseRoute
  '/admin/buildings/$buildingId/residents': typeof AdminBuildingsBuildingIdResidentsRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
  '/api/public/manifest/$buildingId': typeof ApiPublicManifestBuildingIdRoute
  '/admin/buildings/$buildingId/': typeof AdminBuildingsBuildingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/community-voice': typeof CommunityVoiceRoute
  '/connections': typeof ConnectionsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/messages/$connectionId': typeof MessagesConnectionIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
  '/pulse/$buildingId': typeof PulseBuildingIdRoute
  '/admin': typeof AdminIndexRoute
  '/manager/$buildingId/branding': typeof ManagerBuildingIdBrandingRoute
  '/manager/$buildingId/community-intelligence': typeof ManagerBuildingIdCommunityIntelligenceRoute
  '/manager/$buildingId/community-voice': typeof ManagerBuildingIdCommunityVoiceRoute
  '/manager/$buildingId/recognition': typeof ManagerBuildingIdRecognitionRoute
  '/manager/$buildingId': typeof ManagerBuildingIdIndexRoute
  '/admin/buildings/$buildingId/analytics': typeof AdminBuildingsBuildingIdAnalyticsRoute
  '/admin/buildings/$buildingId/branding': typeof AdminBuildingsBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/danger': typeof AdminBuildingsBuildingIdDangerRoute
  '/admin/buildings/$buildingId/events': typeof AdminBuildingsBuildingIdEventsRoute
  '/admin/buildings/$buildingId/legal': typeof AdminBuildingsBuildingIdLegalRoute
  '/admin/buildings/$buildingId/managers': typeof AdminBuildingsBuildingIdManagersRoute
  '/admin/buildings/$buildingId/neighborhood': typeof AdminBuildingsBuildingIdNeighborhoodRoute
  '/admin/buildings/$buildingId/playbook': typeof AdminBuildingsBuildingIdPlaybookRoute
  '/admin/buildings/$buildingId/pulse': typeof AdminBuildingsBuildingIdPulseRoute
  '/admin/buildings/$buildingId/residents': typeof AdminBuildingsBuildingIdResidentsRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
  '/api/public/manifest/$buildingId': typeof ApiPublicManifestBuildingIdRoute
  '/admin/buildings/$buildingId': typeof AdminBuildingsBuildingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/community-voice': typeof CommunityVoiceRoute
  '/connections': typeof ConnectionsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRouteWithChildren
  '/messages/$connectionId': typeof MessagesConnectionIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
  '/pulse/$buildingId': typeof PulseBuildingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/buildings/$buildingId': typeof AdminBuildingsBuildingIdRouteWithChildren
  '/manager/$buildingId/branding': typeof ManagerBuildingIdBrandingRoute
  '/manager/$buildingId/community-intelligence': typeof ManagerBuildingIdCommunityIntelligenceRoute
  '/manager/$buildingId/community-voice': typeof ManagerBuildingIdCommunityVoiceRoute
  '/manager/$buildingId/recognition': typeof ManagerBuildingIdRecognitionRoute
  '/manager/$buildingId/': typeof ManagerBuildingIdIndexRoute
  '/admin/buildings/$buildingId/analytics': typeof AdminBuildingsBuildingIdAnalyticsRoute
  '/admin/buildings/$buildingId/branding': typeof AdminBuildingsBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/danger': typeof AdminBuildingsBuildingIdDangerRoute
  '/admin/buildings/$buildingId/events': typeof AdminBuildingsBuildingIdEventsRoute
  '/admin/buildings/$buildingId/legal': typeof AdminBuildingsBuildingIdLegalRoute
  '/admin/buildings/$buildingId/managers': typeof AdminBuildingsBuildingIdManagersRoute
  '/admin/buildings/$buildingId/neighborhood': typeof AdminBuildingsBuildingIdNeighborhoodRoute
  '/admin/buildings/$buildingId/playbook': typeof AdminBuildingsBuildingIdPlaybookRoute
  '/admin/buildings/$buildingId/pulse': typeof AdminBuildingsBuildingIdPulseRoute
  '/admin/buildings/$buildingId/residents': typeof AdminBuildingsBuildingIdResidentsRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
  '/api/public/manifest/$buildingId': typeof ApiPublicManifestBuildingIdRoute
  '/admin/buildings/$buildingId/': typeof AdminBuildingsBuildingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/community-standards'
    | '/community-voice'
    | '/connections'
    | '/discover'
    | '/events'
    | '/forum'
    | '/groups'
    | '/join'
    | '/manager'
    | '/manager-auth'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resident-access'
    | '/super-admin-login'
    | '/terms'
    | '/admin/clients'
    | '/admin/legal'
    | '/admin/templates'
    | '/building/$buildingId'
    | '/forum/$threadId'
    | '/manager/$buildingId'
    | '/messages/$connectionId'
    | '/onboarding/$buildingId'
    | '/pulse/$buildingId'
    | '/admin/'
    | '/admin/buildings/$buildingId'
    | '/manager/$buildingId/branding'
    | '/manager/$buildingId/community-intelligence'
    | '/manager/$buildingId/community-voice'
    | '/manager/$buildingId/recognition'
    | '/manager/$buildingId/'
    | '/admin/buildings/$buildingId/analytics'
    | '/admin/buildings/$buildingId/branding'
    | '/admin/buildings/$buildingId/danger'
    | '/admin/buildings/$buildingId/events'
    | '/admin/buildings/$buildingId/legal'
    | '/admin/buildings/$buildingId/managers'
    | '/admin/buildings/$buildingId/neighborhood'
    | '/admin/buildings/$buildingId/playbook'
    | '/admin/buildings/$buildingId/pulse'
    | '/admin/buildings/$buildingId/residents'
    | '/admin/buildings/$buildingId/settings'
    | '/api/public/manifest/$buildingId'
    | '/admin/buildings/$buildingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/community-standards'
    | '/community-voice'
    | '/connections'
    | '/discover'
    | '/events'
    | '/forum'
    | '/groups'
    | '/join'
    | '/manager'
    | '/manager-auth'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resident-access'
    | '/super-admin-login'
    | '/terms'
    | '/admin/clients'
    | '/admin/legal'
    | '/admin/templates'
    | '/building/$buildingId'
    | '/forum/$threadId'
    | '/messages/$connectionId'
    | '/onboarding/$buildingId'
    | '/pulse/$buildingId'
    | '/admin'
    | '/manager/$buildingId/branding'
    | '/manager/$buildingId/community-intelligence'
    | '/manager/$buildingId/community-voice'
    | '/manager/$buildingId/recognition'
    | '/manager/$buildingId'
    | '/admin/buildings/$buildingId/analytics'
    | '/admin/buildings/$buildingId/branding'
    | '/admin/buildings/$buildingId/danger'
    | '/admin/buildings/$buildingId/events'
    | '/admin/buildings/$buildingId/legal'
    | '/admin/buildings/$buildingId/managers'
    | '/admin/buildings/$buildingId/neighborhood'
    | '/admin/buildings/$buildingId/playbook'
    | '/admin/buildings/$buildingId/pulse'
    | '/admin/buildings/$buildingId/residents'
    | '/admin/buildings/$buildingId/settings'
    | '/api/public/manifest/$buildingId'
    | '/admin/buildings/$buildingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/community-standards'
    | '/community-voice'
    | '/connections'
    | '/discover'
    | '/events'
    | '/forum'
    | '/groups'
    | '/join'
    | '/manager'
    | '/manager-auth'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resident-access'
    | '/super-admin-login'
    | '/terms'
    | '/admin/clients'
    | '/admin/legal'
    | '/admin/templates'
    | '/building/$buildingId'
    | '/forum/$threadId'
    | '/manager/$buildingId'
    | '/messages/$connectionId'
    | '/onboarding/$buildingId'
    | '/pulse/$buildingId'
    | '/admin/'
    | '/admin/buildings/$buildingId'
    | '/manager/$buildingId/branding'
    | '/manager/$buildingId/community-intelligence'
    | '/manager/$buildingId/community-voice'
    | '/manager/$buildingId/recognition'
    | '/manager/$buildingId/'
    | '/admin/buildings/$buildingId/analytics'
    | '/admin/buildings/$buildingId/branding'
    | '/admin/buildings/$buildingId/danger'
    | '/admin/buildings/$buildingId/events'
    | '/admin/buildings/$buildingId/legal'
    | '/admin/buildings/$buildingId/managers'
    | '/admin/buildings/$buildingId/neighborhood'
    | '/admin/buildings/$buildingId/playbook'
    | '/admin/buildings/$buildingId/pulse'
    | '/admin/buildings/$buildingId/residents'
    | '/admin/buildings/$buildingId/settings'
    | '/api/public/manifest/$buildingId'
    | '/admin/buildings/$buildingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  CommunityStandardsRoute: typeof CommunityStandardsRoute
  CommunityVoiceRoute: typeof CommunityVoiceRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DiscoverRoute: typeof DiscoverRoute
  EventsRoute: typeof EventsRoute
  ForumRoute: typeof ForumRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  JoinRoute: typeof JoinRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ManagerAuthRoute: typeof ManagerAuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResidentAccessRoute: typeof ResidentAccessRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  TermsRoute: typeof TermsRoute
  BuildingBuildingIdRoute: typeof BuildingBuildingIdRoute
  OnboardingBuildingIdRoute: typeof OnboardingBuildingIdRoute
  PulseBuildingIdRoute: typeof PulseBuildingIdRoute
  ApiPublicManifestBuildingIdRoute: typeof ApiPublicManifestBuildingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin-login': {
      id: '/super-admin-login'
      path: '/super-admin-login'
      fullPath: '/super-admin-login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident-access': {
      id: '/resident-access'
      path: '/resident-access'
      fullPath: '/resident-access'
      preLoaderRoute: typeof ResidentAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-auth': {
      id: '/manager-auth'
      path: '/manager-auth'
      fullPath: '/manager-auth'
      preLoaderRoute: typeof ManagerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-voice': {
      id: '/community-voice'
      path: '/community-voice'
      fullPath: '/community-voice'
      preLoaderRoute: typeof CommunityVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-standards': {
      id: '/community-standards'
      path: '/community-standards'
      fullPath: '/community-standards'
      preLoaderRoute: typeof CommunityStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pulse/$buildingId': {
      id: '/pulse/$buildingId'
      path: '/pulse/$buildingId'
      fullPath: '/pulse/$buildingId'
      preLoaderRoute: typeof PulseBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$buildingId': {
      id: '/onboarding/$buildingId'
      path: '/onboarding/$buildingId'
      fullPath: '/onboarding/$buildingId'
      preLoaderRoute: typeof OnboardingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$connectionId': {
      id: '/messages/$connectionId'
      path: '/$connectionId'
      fullPath: '/messages/$connectionId'
      preLoaderRoute: typeof MessagesConnectionIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/manager/$buildingId': {
      id: '/manager/$buildingId'
      path: '/$buildingId'
      fullPath: '/manager/$buildingId'
      preLoaderRoute: typeof ManagerBuildingIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/forum/$threadId': {
      id: '/forum/$threadId'
      path: '/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof ForumThreadIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/building/$buildingId': {
      id: '/building/$buildingId'
      path: '/building/$buildingId'
      fullPath: '/building/$buildingId'
      preLoaderRoute: typeof BuildingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/$buildingId/': {
      id: '/manager/$buildingId/'
      path: '/'
      fullPath: '/manager/$buildingId/'
      preLoaderRoute: typeof ManagerBuildingIdIndexRouteImport
      parentRoute: typeof ManagerBuildingIdRoute
    }
    '/manager/$buildingId/recognition': {
      id: '/manager/$buildingId/recognition'
      path: '/recognition'
      fullPath: '/manager/$buildingId/recognition'
      preLoaderRoute: typeof ManagerBuildingIdRecognitionRouteImport
      parentRoute: typeof ManagerBuildingIdRoute
    }
    '/manager/$buildingId/community-voice': {
      id: '/manager/$buildingId/community-voice'
      path: '/community-voice'
      fullPath: '/manager/$buildingId/community-voice'
      preLoaderRoute: typeof ManagerBuildingIdCommunityVoiceRouteImport
      parentRoute: typeof ManagerBuildingIdRoute
    }
    '/manager/$buildingId/community-intelligence': {
      id: '/manager/$buildingId/community-intelligence'
      path: '/community-intelligence'
      fullPath: '/manager/$buildingId/community-intelligence'
      preLoaderRoute: typeof ManagerBuildingIdCommunityIntelligenceRouteImport
      parentRoute: typeof ManagerBuildingIdRoute
    }
    '/manager/$buildingId/branding': {
      id: '/manager/$buildingId/branding'
      path: '/branding'
      fullPath: '/manager/$buildingId/branding'
      preLoaderRoute: typeof ManagerBuildingIdBrandingRouteImport
      parentRoute: typeof ManagerBuildingIdRoute
    }
    '/admin/buildings/$buildingId': {
      id: '/admin/buildings/$buildingId'
      path: '/buildings/$buildingId'
      fullPath: '/admin/buildings/$buildingId'
      preLoaderRoute: typeof AdminBuildingsBuildingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buildings/$buildingId/': {
      id: '/admin/buildings/$buildingId/'
      path: '/'
      fullPath: '/admin/buildings/$buildingId/'
      preLoaderRoute: typeof AdminBuildingsBuildingIdIndexRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/api/public/manifest/$buildingId': {
      id: '/api/public/manifest/$buildingId'
      path: '/api/public/manifest/$buildingId'
      fullPath: '/api/public/manifest/$buildingId'
      preLoaderRoute: typeof ApiPublicManifestBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/buildings/$buildingId/settings': {
      id: '/admin/buildings/$buildingId/settings'
      path: '/settings'
      fullPath: '/admin/buildings/$buildingId/settings'
      preLoaderRoute: typeof AdminBuildingsBuildingIdSettingsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/residents': {
      id: '/admin/buildings/$buildingId/residents'
      path: '/residents'
      fullPath: '/admin/buildings/$buildingId/residents'
      preLoaderRoute: typeof AdminBuildingsBuildingIdResidentsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/pulse': {
      id: '/admin/buildings/$buildingId/pulse'
      path: '/pulse'
      fullPath: '/admin/buildings/$buildingId/pulse'
      preLoaderRoute: typeof AdminBuildingsBuildingIdPulseRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/playbook': {
      id: '/admin/buildings/$buildingId/playbook'
      path: '/playbook'
      fullPath: '/admin/buildings/$buildingId/playbook'
      preLoaderRoute: typeof AdminBuildingsBuildingIdPlaybookRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/neighborhood': {
      id: '/admin/buildings/$buildingId/neighborhood'
      path: '/neighborhood'
      fullPath: '/admin/buildings/$buildingId/neighborhood'
      preLoaderRoute: typeof AdminBuildingsBuildingIdNeighborhoodRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/managers': {
      id: '/admin/buildings/$buildingId/managers'
      path: '/managers'
      fullPath: '/admin/buildings/$buildingId/managers'
      preLoaderRoute: typeof AdminBuildingsBuildingIdManagersRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/legal': {
      id: '/admin/buildings/$buildingId/legal'
      path: '/legal'
      fullPath: '/admin/buildings/$buildingId/legal'
      preLoaderRoute: typeof AdminBuildingsBuildingIdLegalRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/events': {
      id: '/admin/buildings/$buildingId/events'
      path: '/events'
      fullPath: '/admin/buildings/$buildingId/events'
      preLoaderRoute: typeof AdminBuildingsBuildingIdEventsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/danger': {
      id: '/admin/buildings/$buildingId/danger'
      path: '/danger'
      fullPath: '/admin/buildings/$buildingId/danger'
      preLoaderRoute: typeof AdminBuildingsBuildingIdDangerRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/branding': {
      id: '/admin/buildings/$buildingId/branding'
      path: '/branding'
      fullPath: '/admin/buildings/$buildingId/branding'
      preLoaderRoute: typeof AdminBuildingsBuildingIdBrandingRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
    '/admin/buildings/$buildingId/analytics': {
      id: '/admin/buildings/$buildingId/analytics'
      path: '/analytics'
      fullPath: '/admin/buildings/$buildingId/analytics'
      preLoaderRoute: typeof AdminBuildingsBuildingIdAnalyticsRouteImport
      parentRoute: typeof AdminBuildingsBuildingIdRoute
    }
  }
}

interface AdminBuildingsBuildingIdRouteChildren {
  AdminBuildingsBuildingIdAnalyticsRoute: typeof AdminBuildingsBuildingIdAnalyticsRoute
  AdminBuildingsBuildingIdBrandingRoute: typeof AdminBuildingsBuildingIdBrandingRoute
  AdminBuildingsBuildingIdDangerRoute: typeof AdminBuildingsBuildingIdDangerRoute
  AdminBuildingsBuildingIdEventsRoute: typeof AdminBuildingsBuildingIdEventsRoute
  AdminBuildingsBuildingIdLegalRoute: typeof AdminBuildingsBuildingIdLegalRoute
  AdminBuildingsBuildingIdManagersRoute: typeof AdminBuildingsBuildingIdManagersRoute
  AdminBuildingsBuildingIdNeighborhoodRoute: typeof AdminBuildingsBuildingIdNeighborhoodRoute
  AdminBuildingsBuildingIdPlaybookRoute: typeof AdminBuildingsBuildingIdPlaybookRoute
  AdminBuildingsBuildingIdPulseRoute: typeof AdminBuildingsBuildingIdPulseRoute
  AdminBuildingsBuildingIdResidentsRoute: typeof AdminBuildingsBuildingIdResidentsRoute
  AdminBuildingsBuildingIdSettingsRoute: typeof AdminBuildingsBuildingIdSettingsRoute
  AdminBuildingsBuildingIdIndexRoute: typeof AdminBuildingsBuildingIdIndexRoute
}

const AdminBuildingsBuildingIdRouteChildren: AdminBuildingsBuildingIdRouteChildren =
  {
    AdminBuildingsBuildingIdAnalyticsRoute:
      AdminBuildingsBuildingIdAnalyticsRoute,
    AdminBuildingsBuildingIdBrandingRoute:
      AdminBuildingsBuildingIdBrandingRoute,
    AdminBuildingsBuildingIdDangerRoute: AdminBuildingsBuildingIdDangerRoute,
    AdminBuildingsBuildingIdEventsRoute: AdminBuildingsBuildingIdEventsRoute,
    AdminBuildingsBuildingIdLegalRoute: AdminBuildingsBuildingIdLegalRoute,
    AdminBuildingsBuildingIdManagersRoute:
      AdminBuildingsBuildingIdManagersRoute,
    AdminBuildingsBuildingIdNeighborhoodRoute:
      AdminBuildingsBuildingIdNeighborhoodRoute,
    AdminBuildingsBuildingIdPlaybookRoute:
      AdminBuildingsBuildingIdPlaybookRoute,
    AdminBuildingsBuildingIdPulseRoute: AdminBuildingsBuildingIdPulseRoute,
    AdminBuildingsBuildingIdResidentsRoute:
      AdminBuildingsBuildingIdResidentsRoute,
    AdminBuildingsBuildingIdSettingsRoute:
      AdminBuildingsBuildingIdSettingsRoute,
    AdminBuildingsBuildingIdIndexRoute: AdminBuildingsBuildingIdIndexRoute,
  }

const AdminBuildingsBuildingIdRouteWithChildren =
  AdminBuildingsBuildingIdRoute._addFileChildren(
    AdminBuildingsBuildingIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBuildingsBuildingIdRoute: typeof AdminBuildingsBuildingIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBuildingsBuildingIdRoute: AdminBuildingsBuildingIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ForumRouteChildren {
  ForumThreadIdRoute: typeof ForumThreadIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumThreadIdRoute: ForumThreadIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface ManagerBuildingIdRouteChildren {
  ManagerBuildingIdBrandingRoute: typeof ManagerBuildingIdBrandingRoute
  ManagerBuildingIdCommunityIntelligenceRoute: typeof ManagerBuildingIdCommunityIntelligenceRoute
  ManagerBuildingIdCommunityVoiceRoute: typeof ManagerBuildingIdCommunityVoiceRoute
  ManagerBuildingIdRecognitionRoute: typeof ManagerBuildingIdRecognitionRoute
  ManagerBuildingIdIndexRoute: typeof ManagerBuildingIdIndexRoute
}

const ManagerBuildingIdRouteChildren: ManagerBuildingIdRouteChildren = {
  ManagerBuildingIdBrandingRoute: ManagerBuildingIdBrandingRoute,
  ManagerBuildingIdCommunityIntelligenceRoute:
    ManagerBuildingIdCommunityIntelligenceRoute,
  ManagerBuildingIdCommunityVoiceRoute: ManagerBuildingIdCommunityVoiceRoute,
  ManagerBuildingIdRecognitionRoute: ManagerBuildingIdRecognitionRoute,
  ManagerBuildingIdIndexRoute: ManagerBuildingIdIndexRoute,
}

const ManagerBuildingIdRouteWithChildren =
  ManagerBuildingIdRoute._addFileChildren(ManagerBuildingIdRouteChildren)

interface ManagerRouteChildren {
  ManagerBuildingIdRoute: typeof ManagerBuildingIdRouteWithChildren
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBuildingIdRoute: ManagerBuildingIdRouteWithChildren,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface MessagesRouteChildren {
  MessagesConnectionIdRoute: typeof MessagesConnectionIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConnectionIdRoute: MessagesConnectionIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  CommunityStandardsRoute: CommunityStandardsRoute,
  CommunityVoiceRoute: CommunityVoiceRoute,
  ConnectionsRoute: ConnectionsRoute,
  DiscoverRoute: DiscoverRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRouteWithChildren,
  GroupsRoute: GroupsRoute,
  JoinRoute: JoinRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ManagerAuthRoute: ManagerAuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResidentAccessRoute: ResidentAccessRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  TermsRoute: TermsRoute,
  BuildingBuildingIdRoute: BuildingBuildingIdRoute,
  OnboardingBuildingIdRoute: OnboardingBuildingIdRoute,
  PulseBuildingIdRoute: PulseBuildingIdRoute,
  ApiPublicManifestBuildingIdRoute: ApiPublicManifestBuildingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
