/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin-login'
import { Route as ResidentAccessRouteImport } from './routes/resident-access'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ManagerAuthRouteImport } from './routes/manager-auth'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CommunityStandardsRouteImport } from './routes/community-standards'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PulseBuildingIdRouteImport } from './routes/pulse.$buildingId'
import { Route as OnboardingBuildingIdRouteImport } from './routes/onboarding.$buildingId'
import { Route as MessagesConnectionIdRouteImport } from './routes/messages.$connectionId'
import { Route as ManagerBuildingIdRouteImport } from './routes/manager.$buildingId'
import { Route as ForumThreadIdRouteImport } from './routes/forum.$threadId'
import { Route as BuildingBuildingIdRouteImport } from './routes/building.$buildingId'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as ManagerBuildingIdBrandingRouteImport } from './routes/manager.$buildingId.branding'
import { Route as AdminBuildingsBuildingIdSettingsRouteImport } from './routes/admin.buildings.$buildingId.settings'
import { Route as AdminBuildingsBuildingIdBrandingRouteImport } from './routes/admin.buildings.$buildingId.branding'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin-login',
  path: '/super-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentAccessRoute = ResidentAccessRouteImport.update({
  id: '/resident-access',
  path: '/resident-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAuthRoute = ManagerAuthRouteImport.update({
  id: '/manager-auth',
  path: '/manager-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStandardsRoute = CommunityStandardsRouteImport.update({
  id: '/community-standards',
  path: '/community-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseBuildingIdRoute = PulseBuildingIdRouteImport.update({
  id: '/pulse/$buildingId',
  path: '/pulse/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuildingIdRoute = OnboardingBuildingIdRouteImport.update({
  id: '/onboarding/$buildingId',
  path: '/onboarding/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConnectionIdRoute = MessagesConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => MessagesRoute,
} as any)
const ManagerBuildingIdRoute = ManagerBuildingIdRouteImport.update({
  id: '/$buildingId',
  path: '/$buildingId',
  getParentRoute: () => ManagerRoute,
} as any)
const ForumThreadIdRoute = ForumThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ForumRoute,
} as any)
const BuildingBuildingIdRoute = BuildingBuildingIdRouteImport.update({
  id: '/building/$buildingId',
  path: '/building/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerBuildingIdBrandingRoute =
  ManagerBuildingIdBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => ManagerBuildingIdRoute,
  } as any)
const AdminBuildingsBuildingIdSettingsRoute =
  AdminBuildingsBuildingIdSettingsRouteImport.update({
    id: '/buildings/$buildingId/settings',
    path: '/buildings/$buildingId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBuildingsBuildingIdBrandingRoute =
  AdminBuildingsBuildingIdBrandingRouteImport.update({
    id: '/buildings/$buildingId/branding',
    path: '/buildings/$buildingId/branding',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/connections': typeof ConnectionsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRouteWithChildren
  '/messages/$connectionId': typeof MessagesConnectionIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
  '/pulse/$buildingId': typeof PulseBuildingIdRoute
  '/manager/$buildingId/branding': typeof ManagerBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/branding': typeof AdminBuildingsBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/connections': typeof ConnectionsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRouteWithChildren
  '/messages/$connectionId': typeof MessagesConnectionIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
  '/pulse/$buildingId': typeof PulseBuildingIdRoute
  '/manager/$buildingId/branding': typeof ManagerBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/branding': typeof AdminBuildingsBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/connections': typeof ConnectionsRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRoute
  '/forum': typeof ForumRouteWithChildren
  '/groups': typeof GroupsRoute
  '/join': typeof JoinRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRouteWithChildren
  '/messages/$connectionId': typeof MessagesConnectionIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
  '/pulse/$buildingId': typeof PulseBuildingIdRoute
  '/manager/$buildingId/branding': typeof ManagerBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/branding': typeof AdminBuildingsBuildingIdBrandingRoute
  '/admin/buildings/$buildingId/settings': typeof AdminBuildingsBuildingIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/community-standards'
    | '/connections'
    | '/discover'
    | '/events'
    | '/forum'
    | '/groups'
    | '/join'
    | '/manager'
    | '/manager-auth'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resident-access'
    | '/super-admin-login'
    | '/terms'
    | '/admin/legal'
    | '/building/$buildingId'
    | '/forum/$threadId'
    | '/manager/$buildingId'
    | '/messages/$connectionId'
    | '/onboarding/$buildingId'
    | '/pulse/$buildingId'
    | '/manager/$buildingId/branding'
    | '/admin/buildings/$buildingId/branding'
    | '/admin/buildings/$buildingId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/community-standards'
    | '/connections'
    | '/discover'
    | '/events'
    | '/forum'
    | '/groups'
    | '/join'
    | '/manager'
    | '/manager-auth'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resident-access'
    | '/super-admin-login'
    | '/terms'
    | '/admin/legal'
    | '/building/$buildingId'
    | '/forum/$threadId'
    | '/manager/$buildingId'
    | '/messages/$connectionId'
    | '/onboarding/$buildingId'
    | '/pulse/$buildingId'
    | '/manager/$buildingId/branding'
    | '/admin/buildings/$buildingId/branding'
    | '/admin/buildings/$buildingId/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/community-standards'
    | '/connections'
    | '/discover'
    | '/events'
    | '/forum'
    | '/groups'
    | '/join'
    | '/manager'
    | '/manager-auth'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/resident-access'
    | '/super-admin-login'
    | '/terms'
    | '/admin/legal'
    | '/building/$buildingId'
    | '/forum/$threadId'
    | '/manager/$buildingId'
    | '/messages/$connectionId'
    | '/onboarding/$buildingId'
    | '/pulse/$buildingId'
    | '/manager/$buildingId/branding'
    | '/admin/buildings/$buildingId/branding'
    | '/admin/buildings/$buildingId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  CommunityStandardsRoute: typeof CommunityStandardsRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DiscoverRoute: typeof DiscoverRoute
  EventsRoute: typeof EventsRoute
  ForumRoute: typeof ForumRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  JoinRoute: typeof JoinRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ManagerAuthRoute: typeof ManagerAuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResidentAccessRoute: typeof ResidentAccessRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  TermsRoute: typeof TermsRoute
  BuildingBuildingIdRoute: typeof BuildingBuildingIdRoute
  OnboardingBuildingIdRoute: typeof OnboardingBuildingIdRoute
  PulseBuildingIdRoute: typeof PulseBuildingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin-login': {
      id: '/super-admin-login'
      path: '/super-admin-login'
      fullPath: '/super-admin-login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident-access': {
      id: '/resident-access'
      path: '/resident-access'
      fullPath: '/resident-access'
      preLoaderRoute: typeof ResidentAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-auth': {
      id: '/manager-auth'
      path: '/manager-auth'
      fullPath: '/manager-auth'
      preLoaderRoute: typeof ManagerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-standards': {
      id: '/community-standards'
      path: '/community-standards'
      fullPath: '/community-standards'
      preLoaderRoute: typeof CommunityStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse/$buildingId': {
      id: '/pulse/$buildingId'
      path: '/pulse/$buildingId'
      fullPath: '/pulse/$buildingId'
      preLoaderRoute: typeof PulseBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$buildingId': {
      id: '/onboarding/$buildingId'
      path: '/onboarding/$buildingId'
      fullPath: '/onboarding/$buildingId'
      preLoaderRoute: typeof OnboardingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$connectionId': {
      id: '/messages/$connectionId'
      path: '/$connectionId'
      fullPath: '/messages/$connectionId'
      preLoaderRoute: typeof MessagesConnectionIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/manager/$buildingId': {
      id: '/manager/$buildingId'
      path: '/$buildingId'
      fullPath: '/manager/$buildingId'
      preLoaderRoute: typeof ManagerBuildingIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/forum/$threadId': {
      id: '/forum/$threadId'
      path: '/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof ForumThreadIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/building/$buildingId': {
      id: '/building/$buildingId'
      path: '/building/$buildingId'
      fullPath: '/building/$buildingId'
      preLoaderRoute: typeof BuildingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/$buildingId/branding': {
      id: '/manager/$buildingId/branding'
      path: '/branding'
      fullPath: '/manager/$buildingId/branding'
      preLoaderRoute: typeof ManagerBuildingIdBrandingRouteImport
      parentRoute: typeof ManagerBuildingIdRoute
    }
    '/admin/buildings/$buildingId/settings': {
      id: '/admin/buildings/$buildingId/settings'
      path: '/buildings/$buildingId/settings'
      fullPath: '/admin/buildings/$buildingId/settings'
      preLoaderRoute: typeof AdminBuildingsBuildingIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buildings/$buildingId/branding': {
      id: '/admin/buildings/$buildingId/branding'
      path: '/buildings/$buildingId/branding'
      fullPath: '/admin/buildings/$buildingId/branding'
      preLoaderRoute: typeof AdminBuildingsBuildingIdBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLegalRoute: typeof AdminLegalRoute
  AdminBuildingsBuildingIdBrandingRoute: typeof AdminBuildingsBuildingIdBrandingRoute
  AdminBuildingsBuildingIdSettingsRoute: typeof AdminBuildingsBuildingIdSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLegalRoute: AdminLegalRoute,
  AdminBuildingsBuildingIdBrandingRoute: AdminBuildingsBuildingIdBrandingRoute,
  AdminBuildingsBuildingIdSettingsRoute: AdminBuildingsBuildingIdSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ForumRouteChildren {
  ForumThreadIdRoute: typeof ForumThreadIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumThreadIdRoute: ForumThreadIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface ManagerBuildingIdRouteChildren {
  ManagerBuildingIdBrandingRoute: typeof ManagerBuildingIdBrandingRoute
}

const ManagerBuildingIdRouteChildren: ManagerBuildingIdRouteChildren = {
  ManagerBuildingIdBrandingRoute: ManagerBuildingIdBrandingRoute,
}

const ManagerBuildingIdRouteWithChildren =
  ManagerBuildingIdRoute._addFileChildren(ManagerBuildingIdRouteChildren)

interface ManagerRouteChildren {
  ManagerBuildingIdRoute: typeof ManagerBuildingIdRouteWithChildren
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBuildingIdRoute: ManagerBuildingIdRouteWithChildren,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface MessagesRouteChildren {
  MessagesConnectionIdRoute: typeof MessagesConnectionIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConnectionIdRoute: MessagesConnectionIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  CommunityStandardsRoute: CommunityStandardsRoute,
  ConnectionsRoute: ConnectionsRoute,
  DiscoverRoute: DiscoverRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRouteWithChildren,
  GroupsRoute: GroupsRoute,
  JoinRoute: JoinRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ManagerAuthRoute: ManagerAuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResidentAccessRoute: ResidentAccessRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  TermsRoute: TermsRoute,
  BuildingBuildingIdRoute: BuildingBuildingIdRoute,
  OnboardingBuildingIdRoute: OnboardingBuildingIdRoute,
  PulseBuildingIdRoute: PulseBuildingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
