/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin-login'
import { Route as ResidentAccessRouteImport } from './routes/resident-access'
import { Route as ManagerAuthRouteImport } from './routes/manager-auth'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingBuildingIdRouteImport } from './routes/onboarding.$buildingId'
import { Route as ManagerBuildingIdRouteImport } from './routes/manager.$buildingId'
import { Route as BuildingBuildingIdRouteImport } from './routes/building.$buildingId'

const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin-login',
  path: '/super-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentAccessRoute = ResidentAccessRouteImport.update({
  id: '/resident-access',
  path: '/resident-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAuthRoute = ManagerAuthRouteImport.update({
  id: '/manager-auth',
  path: '/manager-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuildingIdRoute = OnboardingBuildingIdRouteImport.update({
  id: '/onboarding/$buildingId',
  path: '/onboarding/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerBuildingIdRoute = ManagerBuildingIdRouteImport.update({
  id: '/$buildingId',
  path: '/$buildingId',
  getParentRoute: () => ManagerRoute,
} as any)
const BuildingBuildingIdRoute = BuildingBuildingIdRouteImport.update({
  id: '/building/$buildingId',
  path: '/building/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager-auth': typeof ManagerAuthRoute
  '/resident-access': typeof ResidentAccessRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
  '/manager/$buildingId': typeof ManagerBuildingIdRoute
  '/onboarding/$buildingId': typeof OnboardingBuildingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/manager'
    | '/manager-auth'
    | '/resident-access'
    | '/super-admin-login'
    | '/building/$buildingId'
    | '/manager/$buildingId'
    | '/onboarding/$buildingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/manager'
    | '/manager-auth'
    | '/resident-access'
    | '/super-admin-login'
    | '/building/$buildingId'
    | '/manager/$buildingId'
    | '/onboarding/$buildingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/manager'
    | '/manager-auth'
    | '/resident-access'
    | '/super-admin-login'
    | '/building/$buildingId'
    | '/manager/$buildingId'
    | '/onboarding/$buildingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ManagerAuthRoute: typeof ManagerAuthRoute
  ResidentAccessRoute: typeof ResidentAccessRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  BuildingBuildingIdRoute: typeof BuildingBuildingIdRoute
  OnboardingBuildingIdRoute: typeof OnboardingBuildingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin-login': {
      id: '/super-admin-login'
      path: '/super-admin-login'
      fullPath: '/super-admin-login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident-access': {
      id: '/resident-access'
      path: '/resident-access'
      fullPath: '/resident-access'
      preLoaderRoute: typeof ResidentAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-auth': {
      id: '/manager-auth'
      path: '/manager-auth'
      fullPath: '/manager-auth'
      preLoaderRoute: typeof ManagerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$buildingId': {
      id: '/onboarding/$buildingId'
      path: '/onboarding/$buildingId'
      fullPath: '/onboarding/$buildingId'
      preLoaderRoute: typeof OnboardingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/$buildingId': {
      id: '/manager/$buildingId'
      path: '/$buildingId'
      fullPath: '/manager/$buildingId'
      preLoaderRoute: typeof ManagerBuildingIdRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/building/$buildingId': {
      id: '/building/$buildingId'
      path: '/building/$buildingId'
      fullPath: '/building/$buildingId'
      preLoaderRoute: typeof BuildingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManagerRouteChildren {
  ManagerBuildingIdRoute: typeof ManagerBuildingIdRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBuildingIdRoute: ManagerBuildingIdRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ManagerAuthRoute: ManagerAuthRoute,
  ResidentAccessRoute: ResidentAccessRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  BuildingBuildingIdRoute: BuildingBuildingIdRoute,
  OnboardingBuildingIdRoute: OnboardingBuildingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
